# Generated by Django 3.2 on 2022-12-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0017_alter_video_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='info',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_video', to='oyt.video'),
        ),
    ]
