# Generated by Django 3.2 on 2022-12-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0018_auto_20221211_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='info',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
