# Generated by Django 3.2 on 2022-12-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0023_rename_transform_video_encoded_video_raw_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='raw_video',
            new_name='transform_video_encoded',
        ),
    ]
