# Generated by Django 3.2 on 2022-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyt', '0024_rename_raw_video_video_transform_video_encoded'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transform_compression_ratio',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
